config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :words

  authenticated :user do
	root "words#index", as: "authenticated_root"
  end

  root "welcome#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :words
end

app/models/word.rb
class Word < ActiveRecord::Base
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

	def index
    	@words = Word.where(user_id: current_user)
  	end

	def show
		@word = Word.find(params[:id])
	end

	def new
		@word = current_user.words.build
 	end

	def create
		@word = current_user.words.build(word_params)
		if @word.save
			redirect_to @word
		else
			render 'new'
		end
	end

 	def update
		@word = Word.find(params[:id])
		if @word.update(word_params)
			redirect_to @word
		else
			render 'edit'
		end
	end

	def edit
		@word = Word.find(params[:id])
	end

	def destroy
	@word = Word.find(params[:id])
		@word.destroy
		redirect_to root_path
	end

	private

	def word_params
		params.require(:word).permit(:title, :translation )
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.slim
doctype html
html
head
	title Dictionary
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
body
  	nav.navbar.navbar-default
    	.container
    		.navbar-header
      			== link_to "All Words", root_path, class: "navbar-brand"

      		- if user_signed_in?
      			ul.nav.navbar-nav.navbar-right
      				== link_to "New Word", new_word_path, class: "navbar-brand"
      				== link_to "Account", edit_user_registration_path, class: "navbar-brand"
      				== link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-brand"
      		- else
      			ul.nav.navbar-nav.navbar-right
      				== link_to "Sign Up", new_user_registration_path, class: "navbar-brand"
					== link_to "Sign In", new_user_session_path, class: "navbar-brand"

	.container
		p.notice= notice
		p.alert= alert

	    == yield

app/views/welcome/index.html.slim
h1 Let's teach the words

app/views/words/_form.html.slim
= simple_form_for @word do |f|
	 = f.input :title, label: "Word"
	 = f.input :translation, label: "Translation"
	 = f.button :submit

app/views/words/a.html.slim
- @words.each do |word|
	h2= link_to truncate(word.title.titlecase), word
	P= truncate(word.translation.titlecase, length: 20)

app/views/words/edit.html.slim
 .col-md-4.col-md-offset-4
	h1 Edit Word
	= render 'form'
	= link_to "Back", root_path

app/views/words/index.html.erb
<div class="tabs">

  <ul class="nav nav-tabs">
    <li class="active"><a href="tab-a" data-toggle="tab">A</a></li>
    <li><a href="tab-b" data-toggle="tab">B</a></li>
    <li><a href="tab-c" data-toggle="tab">C</a></li>
  </ul>

  <div class="tab-content">

    <div class="tab-pane fade in active" id="tab-a">
      <% q =  "%#{"A%"}%" %>
      <% @word = Word.where(":title LIKE ?", q) %>
      <p><%= @word %></p>
    </div>

    <!-- <div class="tab-pane fade" id="tab-b">
      <p><% word = Word.find(1) %></p>
      <p><%= word.title %></p>
    </div>

    <div class="tab-pane fade" id="tab-c">
      <p><% word = Word.find(1) %></p>
      <p><%= word.title %></p>
    </div> -->

  </div>
</div>

app/views/words/new.html.slim
 .col-md-4.col-md-offset-4
	h1 New Word
	= render 'form'
	= link_to "Back", root_path

app/views/words/show.html.slim
 .col-md-4.col-md-offset-4
	h1= @word.title
	p= @word.translation


	.btn-group
		= link_to "Back", root_path, class: "btn btn-default"
		= link_to "Edit", edit_word_path(@word), class: "btn btn-default"
		= link_to "Delete", word_path(@word), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"